spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true